-- ================================================================================
--              Oracle 통합 테이블 생성 스크립트 (최종 정리본)
--              ※ 기준: 수정된 회원 테이블(account)
--              ※ Java / JSP 고려 X, SQL 구조만 정리
-- ================================================================================


-- ================================================================================
-- 0. 기존 테이블 삭제 (의존성 역순)
-- ================================================================================
DROP TABLE learning_log PURGE;
DROP TABLE kanji PURGE;
DROP TABLE account PURGE;



-- ================================================================================
-- 1. 회원 테이블 (account)
-- ================================================================================
-- [설계 포인트]
-- - accID : 내부 식별용 PK (숫자, FK 기준)
-- - userID : 로그인 ID (이메일 형식 가능, UNIQUE)
-- - 출석 정보(attendance)는 learning_log로 판단 → 컬럼만 남기고 실제 로직은 미사용
-- ================================================================================

CREATE TABLE account (
    accID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userID VARCHAR2(50) NOT NULL UNIQUE,   -- 로그인 ID (FK 연결용)
    userPW1 VARCHAR2(100) NOT NULL,
    userPW2 VARCHAR2(100) NOT NULL,

    email VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),

    attendance VARCHAR2(50),               -- ❗ 실제 출석 판단은 learning_log 기반
    nickname VARCHAR2(50) NOT NULL
);

-- example
-- 회원 1명 = account 테이블 1 row
-- accID = 1
-- userID = 'test@test.com'



-- ================================================================================
-- 2. 한자 테이블 (kanji)
-- ================================================================================
-- [설계 포인트]
-- - kanjiID를 learning_log에서 참조
-- - JLPT / sector / index 기준 조회 최적화
-- ================================================================================

CREATE TABLE kanji (
    kanjiID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    kanjiindex VARCHAR2(20) NOT NULL UNIQUE,
    kanji NCHAR(1) NOT NULL,

    onyomi1 VARCHAR2(10),
    onyomi2 VARCHAR2(10),
    onyomi3 VARCHAR2(10),

    kunyomi1 VARCHAR2(30),
    kunyomi2 VARCHAR2(30),
    kunyomi3 VARCHAR2(30),

    korean_meaning VARCHAR2(20) NOT NULL,
    meaning_description VARCHAR2(100),

    example1 VARCHAR2(20),
    example2 VARCHAR2(20),
    example3 VARCHAR2(20),

    jlpt_level VARCHAR2(2) NOT NULL,
    sector NUMBER NOT NULL,
    index_num NUMBER NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT ck_kanji_jlpt
        CHECK (jlpt_level IN ('N5','N4','N3','N2','N1'))
);

-- 인덱스
CREATE INDEX idx_kanji_jlpt ON kanji (jlpt_level);
CREATE INDEX idx_kanji_sector ON kanji (jlpt_level, sector);
CREATE INDEX idx_kanji_char ON kanji (kanji);

-- 업데이트 트리거
CREATE OR REPLACE TRIGGER trg_kanji_updated_at
BEFORE UPDATE ON kanji
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/



-- ================================================================================
-- 3. 학습 로그 테이블 (learning_log) + 출석 통합
-- ================================================================================
-- [핵심 컨셉]
-- - "출석" 테이블 따로 두지 않음
-- - 하루에 학습 기록이 1개라도 있으면 → 출석 O
-- - 회원 기준은 accID (PK 기준 FK 연결)
-- ================================================================================

CREATE TABLE learning_log (
    logID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    accID NUMBER NOT NULL,      -- 회원 기준 (account.accID)
    kanjiID NUMBER NOT NULL,    -- 학습한 한자

    is_correct NUMBER(1) NOT NULL CHECK (is_correct IN (0, 1)),
    studied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_log_account
        FOREIGN KEY (accID)
        REFERENCES account(accID)
        ON DELETE CASCADE,

    CONSTRAINT fk_log_kanji
        FOREIGN KEY (kanjiID)
        REFERENCES kanji(kanjiID)
        ON DELETE CASCADE
);

-- 인덱스 (출석 / 통계용)
CREATE INDEX idx_log_acc_date ON learning_log (accID, TRUNC(studied_at));
CREATE INDEX idx_log_acc ON learning_log (accID);



-- ================================================================================
-- 4. 출석 판단 로직 (설명용)
-- ================================================================================
-- ★ 출석 기준
-- - learning_log에 해당 날짜(accID 기준) 기록 존재 → 출석 O
--
-- example
-- accID = 1
-- 2026-02-03에 learning_log row 3개 존재
-- → 2026-02-03 출석 O
-- ================================================================================



-- ================================================================================
-- 5. 출석 확인 쿼리 예시
-- ================================================================================
-- ※ 화면 / 캘린더 구현 시 기준 쿼리
-- ================================================================================

-- [1] 오늘 출석 여부
-- 출석 O: 결과 > 0
SELECT COUNT(*) 
FROM learning_log
WHERE accID = 1
AND TRUNC(studied_at) = TRUNC(SYSDATE);


-- [2] 특정 월 출석한 날짜 목록
SELECT DISTINCT TRUNC(studied_at) AS attend_date
FROM learning_log
WHERE accID = 1
AND EXTRACT(YEAR FROM studied_at) = 2026
AND EXTRACT(MONTH FROM studied_at) = 2
ORDER BY attend_date;


-- [3] 이번 달 출석 일수
SELECT COUNT(DISTINCT TRUNC(studied_at)) AS attend_days
FROM learning_log
WHERE accID = 1
AND EXTRACT(YEAR FROM studied_at) = 2026
AND EXTRACT(MONTH FROM studied_at) = 2;



-- ================================================================================
-- 6. 데이터 확인용
-- ================================================================================
SELECT * FROM account;
SELECT * FROM kanji;
SELECT * FROM learning_log;

COMMIT;
